drop schema TEST;
create schema TEST;
create TABLE TEST.EMPLOYEE (EID VARCHAR(10) PRIMARY KEY, FNAME VARCHAR(15) NOT NULL, LNAME VARCHAR(15) NOT NULL, SALARY DECIMAL(10,2) NOT NULL);
INSERT INTO TEST.EMPLOYEE VALUES('1', 'Satyajit', 'Chakraborty', 100);
INSERT INTO TEST.EMPLOYEE VALUES('2', 'Chanchal', 'Chandani', 150);
INSERT INTO TEST.EMPLOYEE VALUES('3', 'Sanjay', 'Singh', 175);


