create schema TEST;

create TABLE TEST.DEPARTMENT (DEPT_ID VARCHAR(10), DEPT_NAME VARCHAR(15));
INSERT INTO TEST.DEPARTMENT VALUES('d1','IT');
INSERT INTO TEST.DEPARTMENT VALUES('d2','Engineering');
INSERT INTO TEST.DEPARTMENT VALUES('d3','QA');

create TABLE TEST.EMPLOYEE (EID VARCHAR(10) PRIMARY KEY, FNAME VARCHAR(15) NOT NULL, LNAME VARCHAR(15) NOT NULL, SALARY DECIMAL(10,2) NOT NULL, DEPT_ID VARCHAR(10) NULL);
INSERT INTO TEST.EMPLOYEE VALUES('e1', 'Satyajit', 'Chakraborty', 100, 'd2');
INSERT INTO TEST.EMPLOYEE VALUES('e2', 'Chanchal', 'Chandani', 150, 'd1');
INSERT INTO TEST.EMPLOYEE VALUES('e3', 'Sanjay', 'Singh', 175, 'd3');




